apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kong-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/instance: kong
      app.kubernetes.io/name: kong
  namespaceSelector:
    matchNames:
      - backend
  endpoints:
    - port: kong-admin
      path: /metrics
      interval: 15s
      scheme: http
